### ISSUE TITLE
Error: Unable to locate sunxi-fel utility

### ISSUE THREAD

**Issue by V-i-v-o** [Thore-Krug/Flash-CHIP#10]
I might be stupid, but I can't seem to get this to work.

Using Ubuntu I get the error:

Error: Unable to locate sunxi-fel utility.
  Install sunxi-fel with:
  CHIP-SDK setup script      [github.com/NextThingCo/CHIP-SDK]

**Comment by BOBdotEXE** [comment]
This worked for me:

`sudo apt-get install sunxi-tools`

Or you can build it yourself here: https://github.com/linux-sunxi/sunxi-tools

**Comment by V-i-v-o** [comment]
I fixed it by not using a Live-USB

**Comment by thuliast** [comment]
Here is my solution. With it I flashed correctly 3 C.H.I.P.s (not PocketChip) using Ubuntu Server 18.04 x64
Follow the instructions from Thore Krug's README.MD and once finished "cd" into the directory you cloned his repository (eg. cd Flash-CHIP) and, before running `./Flash.sh` clone these two repos:
`git clone https://github.com/nextthingcomirror/CHIP-SDK.git` and press Enter
`git clone https://github.com/starbloom/CHIP-usbboot.git` and press Enter

Once finished cloning these two repos INSIDE the folder you originally cloned Thore-Krug's repo run `./Flash.sh` and you're good to go
In case it doesn't work on the first attempt just re-run `./Flash.sh` and then enjoy the magic
