### ISSUE TITLE
Unable to locate sunxi-fel utility-cannot download

### ISSUE THREAD

**Issue by Nom771** [Thore-Krug/Flash-CHIP#11]
I can't get the flasher to work, and always run into the "cannot locate sunxi-fel utility". I can't download it using the link provided as the github link given is dead. Any help?

**Comment by BOBdotEXE** [comment]
This worked for me:

`sudo apt-get install sunxi-tools`

Or you can build it yourself here: https://github.com/linux-sunxi/sunxi-tools

**Comment by thuliast** [comment]
Here is my solution. With it I flashed correctly 3 C.H.I.P.s (not PocketChip) using Ubuntu Server 18.04 x64
Follow the instructions from Thore Krug's README.MD and once finished "cd" into the directory you cloned his repository (eg. cd Flash-CHIP) and, before running `./Flash.sh` clone these two repos:
`git clone https://github.com/nextthingcomirror/CHIP-SDK.git` and press Enter
`git clone https://github.com/starbloom/CHIP-usbboot.git` and press Enter

Once finished cloning these two repos INSIDE the folder you originally cloned Thore-Krug's repo run `./Flash.sh` and you're good to go
In case it doesn't work on the first attempt just re-run `./Flash.sh` and then enjoy the magic

**Comment by Thore-Krug** [comment]
@thuliast The extra Repos are not necessary nor called from the script.
