### ISSUE TITLE
Not working on latest OSX

### ISSUE THREAD

**Issue by stephantual** [Thore-Krug/Flash-CHIP#13]
After installing the right toolschain for embedded i got all excited to run the installer on osx mojave, only to get 

` ln -nfs sunxi-fexc /usr/local/bin/fex2bin
arm-none-eabi-gcc -std=c99 -Wall -Wextra -Wno-unused-result -D_POSIX_C_SOURCE=200112L -D_BSD_SOURCE -D_DEFAULT_SOURCE -Iinclude/ -static  -o sunxi-meminfo meminfo.c
meminfo.c:22:10: fatal error: sys/mman.h: No such file or directory
 #include <sys/mman.h>
          ^~~~~~~~~~~~
'
2 hours of googling didn't help... suggestions welcome.

**Comment by stephantual** [comment]
mmm... tried to even install the header lib from the latest xcode... still no dice.. i think everyday apple strays further from the light :) 

I imagine this is not fixable? Will try in nix. shame because it's - bar none - the best pico8 platform out there  since the releaes of the last pico8 binary.

**Comment by frameDoubt** [comment]
I also can't get to work on mac.
` Installing C.H.I.P Tools for MacOS 
fatal: could not create work tree dir 'Chip-tools-Mac': Permission denied
./Flasher.sh: line 19: cd: Chip-tools-Mac: No such file or directory
./Flasher.sh: line 111: cd: Chip-tools-Mac: No such file or directory
Installing the sunxi tools and install it in your Path 
fatal: could not create work tree dir 'sunxi-tools': Permission denied
./Flasher.sh: line 29: cd: sunxi-tools: No such file or directory
-L/usr/local/Cellar/libusb/1.0.23/lib -lusb-1.0
-lz
make: *** No rule to make target `install-all'.  Stop.

**Comment by Thore-Krug** [comment]
@stephantual @brandonsnow @harryvederci  This Repo is not for the Mac-OS Flasher. 
Its over here https://github.com/Thore-Krug/Install-Flash-Chip-Mac . 
Also i wanna point out that i cant check if the Software works on newer Versions since Apple dropped support for my Macbook-Pro wit the Version 10.13.6  So im not able to test Mojave. Im really sorry for this.
