### ISSUE TITLE
Strange error while attempting flash

### ISSUE THREAD

**Issue by elinavvy** [Thore-Krug/Flash-CHIP#14]
I'm trying to flash from a rpi2 and after it confirms fel it says NAND detected:
Followed by several lines of unrecognized characters 
I put an image below

![15707348716238268800684603921913](https://user-images.githubusercontent.com/47046098/66599217-b4946780-eb70-11e9-8742-357ee6d6d878.jpg)

**Comment by Thore-Krug** [comment]
Hi, 

this seems like a Brownout ( The under delivery with power ) make sure u have a sufficient power supply. This fixed the Issue for other Problems, but in general i recommend to use a PC/Laptop.
