### ISSUE TITLE
Flashing CHIP on Raspberry Pi - usb_bulk_send() ERROR -7

### ISSUE THREAD

**Issue by Superlub** [Thore-Krug/Flash-CHIP#15]
root@raspberrypi:/home/pi/Flash-CHIP/CHIP-tools# sunxi-fel -l
USB device 001:027   Allwinner A13     16254291:50303743:39383030:0d4267de

root@raspberrypi:/home/pi/Flash-CHIP/CHIP-tools# FEL='sudo sunxi-fel' FASTBOOT='sudo fastboot' SNIB=false ./chip-update-firmware.sh -gn
== Gui selected ==
== No Limit mode ==
== preparing images ==
== Local/cached probe files located ==
== Staging for NAND probe ==
Image Name:   detect NAND
Created:      Tue Oct 15 21:28:18 2019
Image Type:   ARM Linux Script (uncompressed)
Data Size:    97 Bytes = 0.09 kB = 0.00 MB
Load Address: 00000000
Entry Point:  00000000
Contents:
   Image 0: 89 Bytes = 0.09 kB = 0.00 MB
waiting for fel...OK
usb_bulk_send() ERROR -7: Operation timed out

**Comment by 53K70R29** [comment]
Could it be your USB cable is inadequate? Received this a couple of times then changed to a better cable and this solved it!

**Comment by Thore-Krug** [comment]
Its Power related, Pls use a Proper Power supply and cable

**Comment by Superlub** [comment]
I tried several USB cables on various Pi's and a VM virtualbox (Debian) on Windows 10.

All ending with the usb_bulk_send() error -7.

Maybe this is relevant:

https://github.com/linux-sunxi/sunxi-tools/blob/master/fel_lib.c
{
	/*
	 * With no progress notifications, we'll use the maximum chunk size.
	 * Otherwise, it's useful to lower the size (have more chunks) to get
	 * more frequent status updates. 128 KiB per request seem suitable.
	 * (Worst case of "slow" transfers -> one update every two seconds.)
	 */
	size_t max_chunk = progress ? 128 * 1024 : AW_USB_MAX_BULK_SEND;

	size_t chunk;
	int rc, sent;
	while (length > 0) {
		chunk = length < max_chunk ? length : max_chunk;
		rc = libusb_bulk_transfer(usb, ep, (void *)data, chunk,
					  &sent, USB_TIMEOUT);
		if (rc != 0)
			usb_error(rc, "usb_bulk_send()", 2);
		length -= sent;
		data += sent;

		if (progress)
			progress_update(sent); /* notification after each chunk */
	}
}
