### ISSUE TITLE
I tried several USB cables on various Pi's and a VM virtualbox (Debian) on Windows 10.

### ISSUE THREAD

**Issue by Superlub** [Thore-Krug/Flash-CHIP#16]
I tried several USB cables on various Pi's and a VM virtualbox (Debian) on Windows 10.

All ending with the usb_bulk_send() error -7.

Maybe this is relevant:

https://github.com/linux-sunxi/sunxi-tools/blob/master/fel_lib.c
{
	/*
	 * With no progress notifications, we'll use the maximum chunk size.
	 * Otherwise, it's useful to lower the size (have more chunks) to get
	 * more frequent status updates. 128 KiB per request seem suitable.
	 * (Worst case of "slow" transfers -> one update every two seconds.)
	 */
	size_t max_chunk = progress ? 128 * 1024 : AW_USB_MAX_BULK_SEND;

	size_t chunk;
	int rc, sent;
	while (length > 0) {
		chunk = length < max_chunk ? length : max_chunk;
		rc = libusb_bulk_transfer(usb, ep, (void *)data, chunk,
					  &sent, USB_TIMEOUT);
		if (rc != 0)
			usb_error(rc, "usb_bulk_send()", 2);
		length -= sent;
		data += sent;

		if (progress)
			progress_update(sent); /* notification after each chunk */
	}
}

_Originally posted by @Superlub in https://github.com/Thore-Krug/Flash-CHIP/issues/15#issuecomment-543924044_

**Comment by AtomSub** [comment]
Did you follow these steps?
Remove the C.H.I.P from its case (in case you have a Pocket C.H.I.P).
Connect the FEL and a GROUND pin of the C.H.I.P (for example, with a paperclip).
