### ISSUE TITLE
2019_November, both my old way and this new way fail

### ISSUE THREAD

**Issue by jtannenba** [Thore-Krug/Flash-CHIP#18]
root@SandboxPi:~/Chip/Flash-CHIP# ./Flash.sh
   #  #  #
  #########
###       ###
  # {#}   #
###  '\######
  #       #
########
   #  #  #
 Welcome to the C.H.I.P Flasher Tool
 Please enter your wanted flavour
 ++++++++++++++++++++++++++++++++++++++++++
 enter p for pocketchip Image
 enter s for the headless Server Image
 enter g for the Desktop Image
 enter b for the Buildroot Image
 ++++++++++++++++++++++++++++++++++++++++++
 IMPORTANT INFO
 If u suffer from Power Problems add a n
 to your choice of flavour
 Example: gn for the No-Limit Desktop Image
 ++++++++++++++++++++++++++++++++++++++++++
 Other options
 ++++++++++++++++++++++++++++++++++++++++++
 enter f for Force Clean
 ++++++++++++++++++++++++++++++++++++++++++
 Then press enter please
g

 Setting up environment
Hit:1 http://raspbian.raspberrypi.org/raspbian stretch InRelease
Hit:2 http://archive.raspberrypi.org/debian stretch InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
curl is already the newest version (7.52.1-5+deb9u9).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree... Done
u-boot-tools is already the newest version (2016.11+dfsg1-4+rpi1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree... Done
adb is already the newest version (1:7.0.0+r33-1).
android-tools-fastboot is already the newest version (1:7.0.0+r33-1).
fastboot is already the newest version (1:7.0.0+r33-1).
git is already the newest version (1:2.11.0-3+deb9u4).
sunxi-tools is already the newest version (1.4.1-1).
u-boot-tools is already the newest version (2016.11+dfsg1-4+rpi1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

 Adding current user to dialout group

 Adding current user to plugdev group

 Adding udev rule for Allwinner device
SUBSYSTEM=="usb", ATTRS{idVendor}=="1f3a", ATTRS{idProduct}=="efe8", GROUP="plugdev", MODE="0660" SYMLINK+="usb-chip"
SUBSYSTEM=="usb", ATTRS{idVendor}=="18d1", ATTRS{idProduct}=="1010", GROUP="plugdev", MODE="0660" SYMLINK+="usb-chip-fastboot"
SUBSYSTEM=="usb", ATTRS{idVendor}=="1f3a", ATTRS{idProduct}=="1010", GROUP="plugdev", MODE="0660" SYMLINK+="usb-chip-fastboot"
SUBSYSTEM=="usb", ATTRS{idVendor}=="067b", ATTRS{idProduct}=="2303", GROUP="plugdev", MODE="0660" SYMLINK+="usb-serial-adapter"

 Installing CHIP-tools
Already up-to-date.
== Gui selected ==
== preparing images ==
== Local/cached probe files located ==
== Staging for NAND probe ==
Image Name:   detect NAND
Created:      Thu Nov  7 14:21:49 2019
Image Type:   ARM Linux Script (uncompressed)
Data Size:    97 Bytes = 0.09 kB = 0.00 MB
Load Address: 00000000
Entry Point:  00000000
Contents:
   Image 0: 89 Bytes = 0.09 kB = 0.00 MB
waiting for fel...OK
waiting for fel......OK
NAND detected:
9g?▒▒▒
`▒H]N▒▒@bX9s▒▒▒ümu▒ѝ▒▒▒▒:▒▒▒J6▒▒▒Je▒d▒G▒▒z@
H▒▒T▒=ian▒▒a▒▒C▒▒
▒▒ʿ▒▒$▒▒▒%▒▒▒R▒"m▒▒@▒▒eķ?u▒▒SE▒▒▒H▒▒▒▒~▒▒▒▒ڔH+▒w!c▒p@▒ߺ
N▒▒c4▒▒▒▒▒m▒a▒▒▒T▒[▒▒AF▒▒▒▒\▒▒4h▒▒d▒6n4U▒▒)▒▒l▒▒@▒▒▒5p▒▒PuTTYPuTTY/tmp/chip-uboot-script-NVtO45/nand-info: line 1: $'9\024g?\200\367\333\036\017': command not found
/tmp/chip-uboot-script-NVtO45/nand-info: line 2: unexpected EOF while looking for matching ``'
/tmp/chip-uboot-script-NVtO45/nand-info: line 4: syntax error: unexpected end of file
root@SandboxPi:~/Chip/Flash-CHIP# PuTTYPuTTY036\017': command not found
> /tmp/chip-uboot-script-NVtO45/nand-info: line 2: unexpected EOF while looking for matching ``'
-bash: PuTTYPuTTY036017: command not found

Raspbian updated something that broke the reflashing of the CHIP?  I was trying option 'g'
Would be interested if you ran across this?  As you can see, all the tools are up to date.

**Comment by Thore-Krug** [comment]
Can u pls remove the Mac current setting.for the Pi

**Comment by jtannenba** [comment]
How do you do that?  This is the Pi I originally was able to flash the chip with.  I finally tried on my media server which is also Stretch, but a full size computer and it flashed.  I looked on the web and 
could not find remove Mac current.

**Comment by vlad-x** [comment]
I've had the same problem, the install script printed some binary code after `NAND detected` - I made it work by using a USB 2.0 hub + a different micro-usb cable, everything worked perfectly after that!

**Comment by jtannenba** [comment]
Is anyone doing anything with the chip?   I haven't done anything since I loaded it.
