### ISSUE TITLE
support nextthing chip debian stretch?

### ISSUE THREAD

**Issue by icode** [Thore-Krug/Flash-CHIP#2]
support nextthing chip (not pro) debian 9 (stretch)?
I need NetworkManager 1.x

**Comment by Thore-Krug** [comment]
Yes u can update it. 


```sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade

sudo sed -i 's/jessie/stretch/g' /etc/apt/sources.list

sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade

sudo apt-get autoremove

sudo reboot
```

**Comment by gstammw** [comment]
Upgrading works, but consumes a lot of time. Providng a debian stretch-image for a headless-server would come handy.

**Comment by Thore-Krug** [comment]
I will take a look on it.

**Comment by gstammw** [comment]
Great, thank you. We also need a new kernel or at least security patches for the existing kernel image, because stretch doesn't bringt an image for C.H.I.P.

**Comment by Thore-Krug** [comment]
Too be clear the NAND Driver is closed source so we cant expect new Kernel Versions to run on Chip, u could run it from a USB Stick though. What i want is to build a new flashable Image with a new debootstrap of stretch or buster.
