### ISSUE TITLE
Flashing Headless Servermode No Wlan

### ISSUE THREAD

**Issue by superpedro** [Thore-Krug/Flash-CHIP#28]
Hello,

after trying all my micro usb cable chip finised flashing with the headless mode. No errors and the roll quote in the end.

But the CHIP didn´t connect to my network - can´t found at the fritzbox router. Connecting the HDMI it end in the command promt, but no updates because of no network.

What to do.

Thanks for help
Greetings
Peter

**Comment by Thore-Krug** [comment]
Hi, 

Have you checked if the Fritzbox offers WiFi on the supported bands by the chip WiFi IC ? It's a bit older so some bands might be disabled by default on your Fritzbox. Also what was your approach to connect to your WiFi?
