### ISSUE TITLE
ERROR: please make sure CHIP is connected and jumpered in FEL mode

### ISSUE THREAD

**Issue by curemode2002** [Thore-Krug/Flash-CHIP#5]
I connect the CHIP as recommended to my USB port, with the jumper between FEL and GND. When the CHIP powers on I get a pink and white LED, then I run the ./Flash.sh command as outlined and it always ends in with FEL....TIMEOUT, ERROR: please make sure CHIP is connected and jumpered in FEL mode
My Linux is running as a virtual machine on a windows host via Virtualbox. I have given the virtual machine direct access to both the network hardware and usb hardware. Any help would be greatly appreciated!

**Comment by Thore-Krug** [comment]
HI, 

thank you for the detailed issue. 

u have to install the windows driver for chip 

unzip the attached file run the installer reboot your PC and it will work. 

[InstallDriver2.exe.zip](https://github.com/Thore-Krug/Flash-CHIP/files/3066121/InstallDriver2.exe.zip)

**Comment by curemode2002** [comment]
Thanks for the driver I was able to find the chip device finally but now I keep getting the following error trying to flash the chip. I think this might be a new issue but wanted to run it by you first. 
![ChipError](https://user-images.githubusercontent.com/49456439/55969815-ab672400-5c3b-11e9-928a-ecba6308fa81.jpg)
I do notice just before this error it runs the the fastboot check, the chip disconnects via usb and reconnects but Windows warns that it was not identified. Also when I try and boot the chip in the pocket I just get the chip icon and nothing else.

**Comment by Thore-Krug** [comment]
Did u then tried to add the C.H.I.P in this state to the VM via the Menu ?

**Comment by curemode2002** [comment]
No let me give that a try

**Comment by curemode2002** [comment]
No luck during the fast boot it shows up as an Allwinner Technology USB download gadget [0215] and I cannot select it.

**Comment by curemode2002** [comment]
No luck during the fast boot it shows up as an Allwinner Technology USB download gadget [0215] and I cannot select it.

**Comment by curemode2002** [comment]
Okay a little more info, I was able to add the Allwinner Technology USB download gadget [0215] to the filters in the Virtual Box VM but now the errors have changed a bit.
![ChipError2](https://user-images.githubusercontent.com/49456439/55980844-934ecf00-5c52-11e9-86a7-54350fb481d0.jpg)

**Comment by Thore-Krug** [comment]
I try to recreate this.

**Comment by curemode2002** [comment]
I will also see if I can grab a old laptop or pc to setup as a straight up Ubuntu install so I can try without a VM

**Comment by Thore-Krug** [comment]
U can also use a Live System from a USB Stick, under Windows u can use [Rufus](https://rufus.ie/)

**Comment by curemode2002** [comment]
Didn't think of that I can see what I can do there, I don't have a drive but I will grab one from home tomorrow.

**Comment by Thore-Krug** [comment]
My USB cable ist broken i will buy a new one and see what i can do. On native Linux and Live Linux it works as well in a VM using a Mac as Host.

**Comment by Thore-Krug** [comment]
Oh by the way are u using a USB3 Port ? Better use USB2

**Comment by Thore-Krug** [comment]
Oh and are u using the VirtualBox Extension Pack ?

**Comment by curemode2002** [comment]
Yes and yes

**Comment by Thore-Krug** [comment]
@curemode2002  Could u please try to run ```lsusb ``` and ```dmesg ``` then send me the output ?

**Comment by lukasz-szyszkowski** [comment]
When you see message "waiting for fastboot...." go to Devices > USB > USB Settings (from menu on top) and click ADD on the right (usb connector with plus sign), add all devices on the list and it should go forward.

from rxOS site:
`If you are using a virtualmachine (e.g., VirtualBox or VMware), you should be aware that, during the flashing, when the “Waiting for fastboot” message appears, the CHIP will change its USB ID. This means that the USB ID you originally set up while it was in FEL mode will no longer apply, and the guest OS will loose the connection to CHIP. This results in fastboot timeout.`

**Comment by Thore-Krug** [comment]
OK thx for the detailed decribtion. Ive mentioned that above but not nearly as detailed. I thought that it should be clear to anybody how to add USB devices when their use Virtualbox.

**Comment by lukasz-szyszkowski** [comment]
That's tricky because new USB device appears after connecting with FEL, it's not available before.

**Comment by Thore-Krug** [comment]
That is clear

**Comment by Thore-Krug** [comment]
I close this Issue because it is not the fault of my Script and the Solution is known.

**Comment by Adsuf** [comment]
Hi, Mr Krug and everyone.

I'm using ubuntu on a VM. Windows 10 as host.

I have the same problem, in my case, it gets stuck on Waiting for fastboot----- TIMEOUT.
Before that the computer recognizes several times a new usb, but at the end it shows a warning that it could not recognize the usb connected.
Before that I had the sunxi-tools problem, but I managed to downgrade sunxi tools to the 1.4.1.1-1 version and it continued the process until this point.

![image](https://user-images.githubusercontent.com/47760839/82847944-815fd800-9eb6-11ea-9246-ef4326310a8e.png)


I tried the solutions on this post but the VM does not recognize any new usb attached.

I very much appreciate your help.

**Comment by eugene-can** [comment]
> Hi, Mr Krug and everyone.
> 
> I'm using ubuntu on a VM. Windows 10 as host.
> 
> I have the same problem, in my case, it gets stuck on Waiting for fastboot----- TIMEOUT.
> Before that the computer recognizes several times a new usb, but at the end it shows a warning that it could not recognize the usb connected.
> Before that I had the sunxi-tools problem, but I managed to downgrade sunxi tools to the 1.4.1.1-1 version and it continued the process until this point.
> 
> ![image](https://user-images.githubusercontent.com/47760839/82847944-815fd800-9eb6-11ea-9246-ef4326310a8e.png)
> 
> I tried the solutions on this post but the VM does not recognize any new usb attached.
> 
> I very much appreciate your help.

Did you find a solution?

**Comment by Anteino** [comment]
> Hi, Mr Krug and everyone.
> 
> I'm using ubuntu on a VM. Windows 10 as host.
> 
> I have the same problem, in my case, it gets stuck on Waiting for fastboot----- TIMEOUT.
> Before that the computer recognizes several times a new usb, but at the end it shows a warning that it could not recognize the usb connected.
> Before that I had the sunxi-tools problem, but I managed to downgrade sunxi tools to the 1.4.1.1-1 version and it continued the process until this point.
> 
> ![image](https://user-images.githubusercontent.com/47760839/82847944-815fd800-9eb6-11ea-9246-ef4326310a8e.png)
> 
> I tried the solutions on this post but the VM does not recognize any new usb attached.
> 
> I very much appreciate your help.

Yea I am also facing the same problem. Did you fix it?

**Comment by Anteino** [comment]
> > Hi, Mr Krug and everyone.
> > I'm using ubuntu on a VM. Windows 10 as host.
> > I have the same problem, in my case, it gets stuck on Waiting for fastboot----- TIMEOUT.
> > Before that the computer recognizes several times a new usb, but at the end it shows a warning that it could not recognize the usb connected.
> > Before that I had the sunxi-tools problem, but I managed to downgrade sunxi tools to the 1.4.1.1-1 version and it continued the process until this point.
> > ![image](https://user-images.githubusercontent.com/47760839/82847944-815fd800-9eb6-11ea-9246-ef4326310a8e.png)
> > I tried the solutions on this post but the VM does not recognize any new usb attached.
> > I very much appreciate your help.
> 
> Did you find a solution?

I ended up using one C.H.I.P. to fix the other. Point is, don't use windows or any VM. Use a system that is already running on linux and flash directly. Anyway, my C.H.I.P. has been revived :)

**Comment by eugene-can** [comment]
> > Hi, Mr Krug and everyone.
> > I'm using ubuntu on a VM. Windows 10 as host.
> > I have the same problem, in my case, it gets stuck on Waiting for fastboot----- TIMEOUT.
> > Before that the computer recognizes several times a new usb, but at the end it shows a warning that it could not recognize the usb connected.
> > Before that I had the sunxi-tools problem, but I managed to downgrade sunxi tools to the 1.4.1.1-1 version and it continued the process until this point.
> > ![image](https://user-images.githubusercontent.com/47760839/82847944-815fd800-9eb6-11ea-9246-ef4326310a8e.png)
> > I tried the solutions on this post but the VM does not recognize any new usb attached.
> > I very much appreciate your help.
> 
> Yea I am also facing the same problem. Did you fix it?

Hey Guys,
Yes, I finally found the solution - my old laptop with Windows XP. I just converted the VM disk and wrote down it to SSD and exchanged it with the old one in the laptop and everything start working. 
Unfortunately, the VM didn't want to cooperate with me. Probably I missed something with my VM. :(
Thnx.
