### ISSUE TITLE
Error 7

### ISSUE THREAD

**Issue by lucie-sharpe** [Thore-Krug/Flash-CHIP#8]
Hi i got an error when trying to flash my chip as shown in the pics. This was my second error my first was sunxi-tools not install but i fixed that by cloning the git hub page.
![DSC_0041](https://user-images.githubusercontent.com/50631980/57713473-73a03180-766a-11e9-8042-cdc90277d11e.JPG)
![DSC_0042](https://user-images.githubusercontent.com/50631980/57713493-7d299980-766a-11e9-9fce-8d4acc4e86d6.JPG)

Thanks for your help

**Comment by Thore-Krug** [comment]
On wich OS are u running the script Nativ or in a VM ? Did u disconnected the chip accidentally ? Are u using a USB2 Port ? Did u tried other cables or USB Ports ? Are u sure that your USB Port can Provide enough current ? Maybe disable Power Saving when u use a Laptop or other mobile Device.

**Comment by lucie-sharpe** [comment]
I am using an old laptop running kali linux 32bit. I have tried different cables. I belive it uses usb 2.0 defently not 3. How can i check if it is providing enough power?

**Comment by Thore-Krug** [comment]
does the command dmesg output something related to power issues ?

**Comment by lucie-sharpe** [comment]
No there was no errors I could see about power. I tried it on a raspberry pi 3 and got this.

Line 3: Syntax error: unexpected end of file

**Comment by lucie-sharpe** [comment]
Acidentaly closed it
I got this error when I tried it on my raspberry pi 3
Line 3: syntax error: unexpected end of file

**Comment by Thore-Krug** [comment]
Did u tried to reinstall the Stuff and try again ?

**Comment by lucie-sharpe** [comment]
![DSC_0045](https://user-images.githubusercontent.com/50631980/57800906-6ce8eb80-774a-11e9-852d-b8dcf63a0b1c.JPG)
yes i re-cloned your github page and ran Flash.sh on raspian and it came up with a line of garbled text and then that error

**Comment by Thore-Krug** [comment]
Thats wierd with the Rasbian . The -7 Error on the Laptop means that the rescource is busy

**Comment by lucie-sharpe** [comment]
I tried running option g again and this happend
![15582754383856844696703036907075](https://user-images.githubusercontent.com/50631980/57983394-37dde100-7a49-11e9-9c54-9c1f8299362f.jpg)

**Comment by lucie-sharpe** [comment]
I tried to force clan and I comes up with line 3: syntax error: unexpected end of file

**Comment by Thore-Krug** [comment]
Can u pls add a Battery to chip ? The Raspberry PI cannot apply enough Power to the Chip !

**Comment by lucie-sharpe** [comment]
I powered it through a power
![15582818570331901054922538115285](https://user-images.githubusercontent.com/50631980/57984893-323bc780-7a58-11e9-8185-61bff9a76589.jpg)
s USB hub and it worked successfully

**Comment by lucie-sharpe** [comment]
Thanks for your help
